//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Game.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_C2S")]
  public partial class Msg_C2S : global::ProtoBuf.IExtensible
  {
    public Msg_C2S() {}
    
    private protocol.ProtoId _protoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"protoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.ProtoId protoId
    {
      get { return _protoId; }
      set { _protoId = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private protocol.SystemHeart _systemHeart = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"systemHeart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.SystemHeart systemHeart
    {
      get { return _systemHeart; }
      set { _systemHeart = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Msg_S2C")]
  public partial class Msg_S2C : global::ProtoBuf.IExtensible
  {
    public Msg_S2C() {}
    
    private protocol.ProtoId _protoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"protoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.ProtoId protoId
    {
      get { return _protoId; }
      set { _protoId = value; }
    }
    private protocol.SystemError_S2C _systemError_S2C = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"systemError_S2C", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protocol.SystemError_S2C systemError_S2C
    {
      get { return _systemError_S2C; }
      set { _systemError_S2C = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SystemHeart")]
  public partial class SystemHeart : global::ProtoBuf.IExtensible
  {
    public SystemHeart() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SystemError_S2C")]
  public partial class SystemError_S2C : global::ProtoBuf.IExtensible
  {
    public SystemError_S2C() {}
    
    private string _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ProtoId")]
    public enum ProtoId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM_HEART", Value=1001)]
      SYSTEM_HEART = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SYSTEM_ERROR_S2C", Value=1002)]
      SYSTEM_ERROR_S2C = 1002
    }
  
}